import {PointScene} from './scene.js';
import {datasets,months,seriesFor,changeFor,plotPoints} from './data.js';
import {createIdentity} from './identity.js';
import './model-intro.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const preference=matchMedia('(prefers-reduced-motion: reduce)');let paused=preference.matches;
const identity=createIdentity({text:$('#identity-role'),index:$('#identity-index'),button:$('#identity-pause'),root:document.documentElement,initialPaused:paused});
const hero=new PointScene($('#universe'),'hero'),morph=new PointScene($('#morph'),'morph');
const journey=$('.journey'),steps=$$('.chapter-steps>span');
const chapters=[['01 — COLLECT','Start with possibility.','Every point is a fragment of a story.<br>Look closer. The patterns are already there.','SCATTERED SIGNALS'],['02 — CONNECT','Find the relationships.','Individual signals begin to connect.<br>Structure gives the noise a new meaning.','CONNECTED SYSTEM'],['03 — UNDERSTAND','Let the insight surface.','A clearer shape. A different perspective.<br>Something you can finally act on.','A CLEARER PERSPECTIVE']];
let chapter=-1,scrollDirty=true,time=0,last=0;let heroVisible=true,morphVisible=false;
const sceneObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.target===$('.hero'))heroVisible=e.isIntersecting;else morphVisible=e.isIntersecting;}));sceneObserver.observe($('.hero'));sceneObserver.observe(journey);
if('IntersectionObserver' in window){document.documentElement.classList.add('js-motion');const reveals=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');reveals.unobserve(e.target);}}),{threshold:.08});$$('.reveal').forEach(e=>reveals.observe(e));}
function scrollState(){const rect=journey.getBoundingClientRect();const progress=Math.min(1,Math.max(0,-rect.top/Math.max(1,rect.height-innerHeight)));morph.morph=progress*2;const next=Math.min(2,Math.floor(progress*3));if(next!==chapter){chapter=next;$('.chapter-index').textContent=chapters[next][0];$('.chapter-copy h3').textContent=chapters[next][1];$('.chapter-copy p').innerHTML=chapters[next][2];$('.diagram-caption').textContent=chapters[next][3];$('.diagram-counter').textContent=`00${next+1} / 003`;steps.forEach((e,i)=>e.classList.toggle('active',i===next));}$('.journey-progress span').style.width=`${progress*100}%`;$('.scroll-progress').style.transform=`scaleX(${scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight)})`;scrollDirty=false;}
addEventListener('scroll',()=>scrollDirty=true,{passive:true});addEventListener('resize',()=>scrollDirty=true);
$('.hero').addEventListener('pointermove',e=>{if(paused||e.pointerType==='touch')return;const rect=$('.hero').getBoundingClientRect();hero.pointer=[(e.clientX/innerWidth-.5)*2,(e.clientY-rect.top)/rect.height-.5];$('#coord-x').textContent=hero.pointer[0].toFixed(3);$('#coord-y').textContent=hero.pointer[1].toFixed(3);},{passive:true});
$('.hero').addEventListener('pointerleave',()=>hero.pointer=[0,0]);
function motionState(){identity.setPaused(paused);document.documentElement.classList.toggle('motion-paused',paused);$('#motion-toggle').setAttribute('aria-pressed',String(paused));$('#motion-toggle').textContent=paused?'Resume motion ▷':'Pause motion Ⅱ';hero.reduced=paused;morph.reduced=paused;scrollDirty=true;}
$('#motion-toggle').addEventListener('click',()=>{paused=!paused;motionState();});preference.addEventListener('change',e=>{paused=e.matches;motionState();});motionState();
function frame(now){const delta=Math.min((now-last)/1000,.05);last=now;if(!document.hidden){if(!paused)time+=delta;if(heroVisible)identity.tick(delta);if(scrollDirty)scrollState();if(heroVisible)hero.draw(time);if(morphVisible)morph.draw(time*.7);}requestAnimationFrame(frame);}requestAnimationFrame(frame);

let lens='growth',range=12,index=11,points=[],values=[];
const svgNS='http://www.w3.org/2000/svg';
const element=(tag,attrs,text)=>{const el=document.createElementNS(svgNS,tag);for(const[k,v]of Object.entries(attrs))el.setAttribute(k,String(v));if(text!==undefined)el.textContent=text;return el;};
function updateSelection(showTooltip=false){const dataset=datasets[lens],p=points[index],month=months[12-range+index];$('#metric-label').textContent=dataset.label;$('#metric-value').textContent=p.value.toFixed(1)+dataset.unit;const diff=changeFor(values,index);$('#metric-change').textContent=`${diff>=0?'↑':'↓'} ${Math.abs(diff).toFixed(1)}% from ${months[12-range].slice(0,3)}`;$('#timeline-month').textContent=month.toUpperCase();$('#timeline-slider').value=String(index);$('#timeline-slider').setAttribute('aria-valuetext',`${month}, ${p.value.toFixed(1)}${dataset.unit}`);$('.chart-crosshair').setAttribute('x1',p.x);$('.chart-crosshair').setAttribute('x2',p.x);$('.chart-active-dot').setAttribute('cx',p.x);$('.chart-active-dot').setAttribute('cy',p.y);$('.chart-tooltip').textContent=`${month.slice(0,3)} · ${p.value.toFixed(1)}${dataset.unit}`;$('.chart-tooltip').hidden=!showTooltip;}
function renderChart(){const dataset=datasets[lens];values=seriesFor(lens,range);points=plotPoints(values);index=Math.min(index,range-1);$('#chart-title').textContent=dataset.title;$('#chart-accessible-title').textContent=dataset.title;$('#chart-desc').textContent=`Simulated ${dataset.label.toLowerCase()}. `+values.map((v,i)=>`${months[12-range+i]}: ${v}${dataset.unit}`).join(', ');const path=points.map((p,i)=>`${i?'L':'M'}${p.x},${p.y}`).join(' ');$('.chart-line').setAttribute('d',path);$('.chart-area-fill').setAttribute('d',`${path} L688,228 L48,228 Z`);const grid=$('.chart-grid');grid.replaceChildren();const minimum=Math.floor(Math.min(...values)*.82),maximum=Math.ceil(Math.max(...values)*1.08);for(let i=0;i<4;i++){const y=30+i*190/3;grid.append(element('line',{x1:48,x2:696,y1:y,y2:y}),element('text',{x:0,y:y+4},Math.round(maximum-i*(maximum-minimum)/3)));}$('.chart-dots').replaceChildren(...points.map(p=>element('circle',{cx:p.x,cy:p.y,r:3})));$('.chart-labels').replaceChildren(...points.map((p,i)=>element('text',{x:p.x,y:254,'text-anchor':'middle'},months[12-range+i].slice(0,3).toUpperCase())));$('#timeline-slider').max=String(range-1);$('.chart-foot>span').textContent=`01 ${months[12-range].slice(0,3).toUpperCase()} — 31 DEC · ILLUSTRATIVE SERIES`;$$('[data-lens]').forEach(b=>{b.classList.toggle('selected',b.dataset.lens===lens);b.setAttribute('aria-pressed',String(b.dataset.lens===lens));});$$('[data-range]').forEach(b=>{b.classList.toggle('selected',+b.dataset.range===range);b.setAttribute('aria-pressed',String(+b.dataset.range===range));});updateSelection();}
$$('[data-lens]').forEach(b=>b.addEventListener('click',()=>{lens=b.dataset.lens;index=range-1;renderChart();}));$$('[data-range]').forEach(b=>b.addEventListener('click',()=>{range=+b.dataset.range;index=range-1;renderChart();}));$('#timeline-slider').addEventListener('input',e=>{index=+e.target.value;updateSelection(true);});$('#signal-chart').addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;const rect=e.currentTarget.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width*720;index=Math.max(0,Math.min(range-1,Math.round((x-48)/640*(range-1))));updateSelection(true);});$('#signal-chart').addEventListener('pointerleave',()=>$('.chart-tooltip').hidden=true);$('#reset-lab').addEventListener('click',()=>{lens='growth';range=12;index=11;renderChart();});renderChart();
