import {PointScene} from './scene.js';
export function introState(progress){const p=Math.max(0,Math.min(1,progress));return{progress:p,morph:Math.min(2,p/.62*2),fly:Math.max(0,(p-.62)/.38)*9,stage:p<.3?0:p<.63?1:2,opacity:p>.82?Math.max(0,1-(p-.82)/.18):1};}
export function startIntro(){const section=document.querySelector('#intro'),canvas=document.querySelector('#intro-points');if(!section||!canvas)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)');let scene,time=0,last=0,dirty=true,visible=true;
const labels=[['01 / COLLECT','Start with the data.','Separate points. A lot to work with.'],['02 / CONNECT','See the connections.','Patterns start to take shape.'],['03 / EXPLORE','Take a closer look.','Scroll through to meet Marwan.']];
function setup(){document.documentElement.classList.toggle('intro-reduced',reduced.matches);if(!reduced.matches&&!scene){scene=new PointScene(canvas,'entry');if(!scene.gl)document.documentElement.classList.add('intro-reduced');}dirty=true;}
function update(){const rect=section.getBoundingClientRect(),p=rect.height>innerHeight?-rect.top/(rect.height-innerHeight):1,s=introState(p);document.documentElement.classList.toggle('entry-active',rect.bottom>innerHeight*.4&&rect.top<=0&&!reduced.matches&&Boolean(scene?.gl));if(scene){scene.morph=s.morph;scene.fly=s.fly;}const [step,title,note]=labels[s.stage];document.querySelector('#intro-step').textContent=step;document.querySelector('#intro-title').textContent=title;document.querySelector('#intro-note').textContent=note;document.querySelector('.intro-copy').style.opacity=String(s.opacity);document.querySelector('.intro-progress span').style.transform=`scaleX(${s.progress})`;document.querySelector('#intro-percent').textContent=String(Math.round(s.progress*100)).padStart(3,'0')+'%';dirty=false;}
const observer=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;});observer.observe(section);addEventListener('scroll',()=>dirty=true,{passive:true});addEventListener('resize',()=>dirty=true);reduced.addEventListener('change',setup);document.querySelector('#skip-intro').addEventListener('click',()=>{document.documentElement.classList.remove('entry-active');document.querySelector('#home').focus({preventScroll:true});});setup();
function frame(now){const delta=Math.min((now-last)/1000,.05);last=now;if(!document.hidden){if(dirty)update();if(visible&&scene&&!reduced.matches){time+=delta;scene.draw(time*.35);}}requestAnimationFrame(frame);}requestAnimationFrame(frame);}
if(typeof document!=='undefined')startIntro();
