import {studies} from './studies.js';
export {shell};
const escape=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const socials=`<a class="button social-button" href="https://github.com/mrwanahmedx" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a class="button social-button" href="https://www.linkedin.com/in/mrwan-ahmed/" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a>`;
const header=`<a class="skip" href="#main">Skip to content</a><header class="header"><a class="brand" href="./index.html" aria-label="Data Observatory home"><img src="./favicon.svg" alt="" width="38" height="38"><span>DATA<br>OBSERVATORY<span class="brand-dot">®</span></span></a><nav aria-label="Main navigation"><a href="./index.html#experience">Experience</a><a href="./index.html#lab">The lab</a><a href="./index.html#work">Selected work</a><a href="./about.html">About</a></nav><a class="header-contact" href="./index.html">Home <span>↗</span></a></header>`;
const mobile=`<nav class="page-jump" aria-label="Explore the site"><a href="./index.html">Home</a><a href="./finance.html">Finance</a><a href="./credit-methodology.html">iScore</a><a href="./risk.html">SQL</a><a href="./people.html">People</a><a href="./about.html">About</a></nav>`;
const footer=`<footer class="detail-footer"><a class="brand" href="./index.html">DATA OBSERVATORY / MARWAN AHMED</a><div class="social-buttons">${socials}</div><span>© 2026 · ALWAYS EXPLORING</span></footer>`;
function shell(title,description,content,script='',style=''){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0a101a"><title>${escape(title)} — Data Observatory</title><meta name="description" content="${escape(description)}"><link rel="icon" href="./favicon.svg"><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Space+Grotesk:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500&display=swap" rel="stylesheet"><link rel="stylesheet" href="./style.css"><link rel="stylesheet" href="./pages.css"></head><body class="inner-page" ${style}>${header}${mobile}<main id="main">${content}</main>${footer}${script}</body></html>`;}
export function projectPage(key){const s=studies[key],next=studies[s.next];return shell(s.title,s.summary,`
 <section class="detail-hero"><a class="back-link" href="./index.html#work">← ALL PROJECTS</a><div class="detail-heading"><div><p class="overline">${s.number} / ${s.category}</p><h1>${s.headline}<br><em>${s.emphasis}</em></h1><p class="detail-summary">${s.summary}</p></div><div class="project-number" aria-hidden="true">${s.number}<span>FIELD NOTES</span></div></div><div class="detail-actions"><a class="button button-lime" href="#playground">Explore the demo <span>↓</span></a><a class="button social-button" href="https://github.com/mrwanahmedx/${s.repository}" target="_blank" rel="noopener noreferrer">Project on GitHub <span>↗</span></a></div></section>
 <section class="context-section"><p class="overline">THE QUESTION</p><div><h2>${s.question}</h2><p>${s.context}</p></div></section>
 <section class="project-brief" aria-labelledby="brief-${key}"><div class="brief-heading"><p class="overline">RECRUITER BRIEF</p><h2 id="brief-${key}">Problem → data → method → engineering → result.</h2></div><div class="brief-grid">${[['Problem',s.brief.problem],['Data',s.brief.data],['Method',s.brief.method],['Engineering challenge',s.brief.engineering],['Result',s.brief.result],['Limitations',s.brief.limitations],['Code',s.brief.code]].map(([label,value],i)=>`<article><span>0${i+1}</span><h3>${label}</h3><p>${value}</p></article>`).join('')}</div></section>
 <section class="playground-section" id="playground" data-study="${key}"><div class="playground-heading"><div><p class="overline">TRY IT YOURSELF</p><h2>${s.demo}</h2></div><span class="demo-badge">SIMULATED DATA</span></div><p class="demo-caveat">This is a companion front-end demo. All numbers below are invented for exploration, not results from the original project.</p>
 <div class="study-controls">${key==='risk'?`<label class="risk-control" for="score-filter">${s.control}<output id="score-output">600</output><input id="score-filter" type="range" min="300" max="850" step="10" value="600"></label>`:`<div><p class="control-label">${s.control}</p><div class="option-group" role="group" aria-label="${s.control}">${s.options.map(([v,l])=>`<button type="button" data-option="${v}" aria-pressed="${v===s.default}" class="${v===s.default?'selected':''}">${l}</button>`).join('')}</div></div>`}<button type="button" class="reset-study">Reset ↺</button></div>
 <div class="study-metrics" aria-live="polite"></div><div class="study-display"><div class="display-toolbar"><p>${key==='risk'?'Matching sample records':'Explore a group to inspect its values'}</p><div class="option-group view-toggle" role="group" aria-label="Display mode"><button type="button" data-view="chart" class="selected" aria-pressed="true">Chart</button><button type="button" data-view="table" aria-pressed="false">Data table</button></div></div><div class="study-legend"></div><div id="study-chart" class="study-chart"></div><div id="study-table" class="table-scroll" hidden></div><output class="selection-note" aria-live="polite">Select a bar to inspect it.</output>${key==='risk'?'<pre class="query-example" aria-label="Equivalent SQL query"></pre>':''}</div>
 <details class="demo-details"><summary>How to read this experiment <span>+</span></summary><p>${s.explanation}</p></details><noscript><p>The interactive demo needs JavaScript. You can still read the project context and follow the source link.</p></noscript></section>
 <section class="craft-section"><p class="overline">ANALYTICS &amp; ENGINEERING ON DISPLAY</p><div>${s.craft.map((c,i)=>`<article><span>0${i+1}</span><h3>${c}</h3></article>`).join('')}</div></section>
 <a class="next-project" href="./${s.next}.html"><div><p class="overline">KEEP EXPLORING / NEXT PROJECT</p><h2>${next.title}</h2></div><span>→</span></a>`, '<script type="module" src="./project.js"></script>',`style="--lime:${s.color}"`);}
export function aboutPage(){return shell('About Marwan','Meet Marwan Ahmed: data analysis, business intelligence, and front-end experimentation.',`
 <section class="detail-hero about-hero"><a class="back-link" href="./index.html">← BACK TO THE OBSERVATORY</a><p class="overline">THE PERSON BEHIND THE EXPERIMENT</p><h1>Analytical mind.<br><em>Creative instincts.</em></h1><p class="detail-summary">I’m Marwan Ahmed. My work sits at the intersection of data analysis, business intelligence, and making information easier to explore.</p><div class="detail-actions social-buttons">${socials}</div></section>
 <section class="context-section"><p class="overline">WHY THIS EXISTS</p><div><h2>Make complex things<br>feel a little more intuitive.</h2><p>Data Observatory is my front-end playground: a place to bring analytical ideas into the browser with motion, interaction, and thoughtful interfaces.</p><p>My main portfolio focuses on Python, SQL, Tableau, Power BI, and Excel. This site explores how those interests translate into experiences people can click through and understand.</p><a class="text-link" href="https://mrwanahmedx.github.io/" target="_blank" rel="noopener noreferrer">Visit my main portfolio ↗</a></div></section>
 <section class="about-paths"><p class="overline">PICK A PATH</p><div class="path-grid"><a href="./index.html#experience"><span>01 / MOTION</span><h2>Explore the<br>observatory.</h2><p>Follow a field of particles from raw signals to a connected structure.</p><b>Enter the experience →</b></a><a href="./index.html#lab"><span>02 / INTERACTION</span><h2>Play with<br>a different lens.</h2><p>Switch datasets and explore the timeline in the signal lab.</p><b>Open the lab →</b></a><a href="./finance.html"><span>03 / PROJECTS</span><h2>Get closer<br>to the work.</h2><p>Browse project context and try the companion interactive demos.</p><b>Explore the projects →</b></a></div></section>
 <section class="about-principles"><p class="overline">WHAT GUIDES THE WORK</p><details open><summary>Clarity before complexity <span>01</span></summary><p>A chart, a query, or a page should help someone understand the next thing that matters.</p></details><details><summary>Interaction with a purpose <span>02</span></summary><p>A good control changes what you can see or understand. Motion should help explain the relationship between states.</p></details><details><summary>Honest about the data <span>03</span></summary><p>Demonstration datasets are labeled. Links to the original project repositories are separate from the visual experiments built for this website.</p></details></section>
 <section class="about-contact"><p class="overline">LET’S CONNECT</p><h2>Have a question or<br><em>something to build?</em></h2><div class="social-buttons">${socials}</div></section>`);}
