export const sum=(rows,key)=>rows.reduce((v,r)=>v+r[key],0);
export function selectRows(rows,split,history='all'){return rows.filter(r=>r.split===split&&(history==='all'||(history==='short'?r.history_months<36:r.history_months>=36)));}
export function curve(rows){const pos=sum(rows,'bad_6m'),neg=rows.length-pos,groups=new Map();for(const r of rows){const g=groups.get(r.pd)||[0,0];g[r.bad_6m]++;groups.set(r.pd,g);}let tp=0,fp=0;const points=[{threshold:null,fpr:0,tpr:0,precision:1,population:0}];for(const [p,[n,y]] of [...groups].sort((a,b)=>b[0]-a[0])){tp+=y;fp+=n;points.push({threshold:p,fpr:neg?fp/neg:null,tpr:pos?tp/pos:null,precision:tp/(tp+fp),population:(tp+fp)/rows.length});}return points;}
export function confusion(rows,t){let tp=0,fp=0,fn=0,tn=0;for(const r of rows){if(r.pd>=t){if(r.bad_6m)tp++;else fp++;}else if(r.bad_6m)fn++;else tn++;}return{tp,fp,fn,tn,precision:tp/(tp+fp||1),recall:tp/(tp+fn||1),fpr:fp/(fp+tn||1)};}
export function metrics(rows){if(!rows.length)return{n:0,events:0,prevalence:null,roc_auc:null,average_precision:null,brier:null,gini:null,ks:null};const events=sum(rows,'bad_6m'),c=curve(rows);let area=0,ap=0,ks=0;for(let i=1;i<c.length;i++){const a=c[i-1],b=c[i];area+=(b.fpr-a.fpr)*(b.tpr+a.tpr)/2;ap+=(b.tpr-a.tpr)*b.precision;ks=Math.max(ks,Math.abs(b.tpr-b.fpr));}const valid=events>0&&events<rows.length;return{n:rows.length,events,prevalence:events/rows.length,roc_auc:valid?area:null,average_precision:events?ap:null,brier:rows.reduce((s,r)=>s+(r.pd-r.bad_6m)**2,0)/rows.length,gini:valid?2*area-1:null,ks:valid?ks:null};}
export function wilson(events,n){if(!n)return[null,null];const z=1.959963984540054,p=events/n,d=1+z*z/n,center=(p+z*z/(2*n))/d,half=z*Math.sqrt(p*(1-p)/n+z*z/(4*n*n))/d;return[Math.max(0,center-half),Math.min(1,center+half)];}
export function calibration(rows){return Array.from({length:10},(_,bin)=>{const p=rows.filter(r=>Math.min(9,Math.floor(r.pd*10))===bin),events=sum(p,'bad_6m'),[low,high]=wilson(events,p.length);return{bin,n:p.length,events,predicted:p.length?sum(p,'pd')/p.length:null,observed:p.length?events/p.length:null,wilson_low:low,wilson_high:high};}).filter(b=>b.n);}
export function psi(reference,sample){if(!reference.length||!sample.length)return{value:null,bins:[]};const bins=Array.from({length:10},(_,bin)=>{const a=reference.filter(p=>Math.min(9,Math.floor(p*10))===bin).length,b=sample.filter(p=>Math.min(9,Math.floor(p*10))===bin).length,e=(a+.5)/(reference.length+5),o=(b+.5)/(sample.length+5);return{bin,reference_share:e,sample_share:o,contribution:(o-e)*Math.log(o/e)};});return{value:sum(bins,'contribution'),bins};}
export function deciles(rows){const sorted=[...rows].sort((a,b)=>b.pd-a.pd||a.borrower_id.localeCompare(b.borrower_id)),n=rows.length,events=sum(rows,'bad_6m');let count=0,captured=0;const result=[];for(let i=0;i<Math.min(10,n);i++){const size=Math.floor(n/10)+(i<n%10?1:0),part=sorted.slice(count,count+size);count+=part.length;const bad=sum(part,'bad_6m');captured+=bad;result.push({decile:i+1,n:part.length,events:bad,event_rate:bad/part.length,lift:events?bad/part.length/(events/n):null,population:count/n,capture:events?captured/events:null});}return result;}
export function segments(rows){return [...new Set(rows.map(r=>r.product_group))].sort().map(name=>{const p=rows.filter(r=>r.product_group===name);return{segment:name,borrowers:p.length,exposure_egp:sum(p,'exposure'),mean_probability:sum(p,'pd')/p.length,event_rate:sum(p,'bad_6m')/p.length};});}
