export const studies = {
 finance: {number:'01',title:'Suez Canal Bank',headline:'A clearer view of',emphasis:'financial performance.',category:'POWER BI / FINANCIAL ANALYSIS',color:'#d7ff82',summary:'A finance dashboard project focused on banking KPIs, revenue versus earnings, and year-over-year performance.',repository:'Suez-Canal-Bank-Finance-Dashboard',question:'How do revenue and earnings move together?',context:'The original project explores financial performance in Power BI. This companion web experiment lets you compare a fictional quarterly series and inspect the relationship between revenue and earnings.',demo:'Quarterly performance',control:'Choose a year',options:[['2024','2024'],['2025','2025']],default:'2025',explanation:'Compare the two series quarter by quarter. The difference between revenue and earnings shows why a rising top line is only part of the picture.',craft:['State-driven charts','Accessible data tables','Responsive dashboard layout'],next:'score'},
 score: {number:'02',title:'iScore Dashboard',headline:'See the shape of',emphasis:'the whole cohort.',category:'TABLEAU / INTERACTIVE DASHBOARD',color:'#8ee6dc',summary:'An interactive Tableau Public dashboard for the iScore project, paired here with an original web-based cohort explorer.',repository:'iScore-Dashboard',question:'What changes when you look at a different cohort?',context:'The original repository presents the iScore Tableau dashboard. The demonstration below uses invented score bands to explore how a population’s distribution can change between cohorts. It does not reproduce the original dataset.',demo:'Cohort distribution',control:'Choose a cohort',options:[['all','All profiles'],['new','New profiles'],['established','Established profiles']],default:'all',explanation:'A distribution shows where observations concentrate. Switch cohorts to see the profile count and the shape of the distribution update together.',craft:['Linked summary metrics','Cohort filtering','Interactive chart selection'],next:'risk'},
 risk: {number:'03',title:'Credit Risk Management',headline:'Explore the logic',emphasis:'behind the query.',category:'SQL / DATABASE DESIGN',color:'#ffce8a',summary:'A SQL database project exploring customers, loans, payments, and credit scores through sample banking data.',repository:'Credit-Risk-Management-Database-SQL-Project',question:'How does a filter change the records you see?',context:'The original project models sample banking information in SQL. Here, a small fictional dataset makes one database concept tangible: adjust a score filter and inspect the matching rows.',demo:'Query playground',control:'Minimum demonstration score',default:600,explanation:'The score slider behaves like a WHERE clause: only records meeting the selected minimum remain. This is a demonstration of filtering, not a lending rule or credit assessment.',craft:['Live query filtering','Empty-result handling','Keyboard-friendly controls'],next:'people'},
 people: {number:'04',title:'Understanding Attrition',headline:'Look beyond',emphasis:'the headline number.',category:'PYTHON / EXPLORATORY ANALYSIS',color:'#bba5ff',summary:'A Python notebook exploring IBM HR data, including job roles, income, overtime, and patterns associated with employee attrition.',repository:'HR-Attrition-Analysis-Using-Python',question:'Does the pattern change when you change the grouping?',context:'The original analysis investigates employee attrition with Python. This companion demo uses fictional aggregate counts to show how the same population can be grouped in different ways. Association does not establish causation.',demo:'Workforce lens',control:'Group the sample by',options:[['department','Department'],['overtime','Overtime']],default:'department',explanation:'Switch between department and overtime to change the level of detail. The total population stays the same; the rates within each group reveal different perspectives.',craft:['Alternative data groupings','Derived rate calculations','Chart and table parity'],next:'finance'}
};
export const sampleLoans=[{id:'DEMO-001',score:720,balance:42000},{id:'DEMO-002',score:610,balance:28000},{id:'DEMO-003',score:540,balance:18000},{id:'DEMO-004',score:780,balance:56000},{id:'DEMO-005',score:660,balance:35000},{id:'DEMO-006',score:590,balance:23000},{id:'DEMO-007',score:810,balance:68000},{id:'DEMO-008',score:690,balance:31000}];
export function getStudyView(key,selection){
 if(!studies[key])throw new Error('Unknown study');
 if(key==='finance'){
  const sets={'2024':[[42,46,49,54],[9,11,12,14]],'2025':[[51,55,59,66],[12,14,16,19]]};const s=sets[selection];if(!s)throw new Error('Invalid year');const revenue=s[0].reduce((a,b)=>a+b,0),earnings=s[1].reduce((a,b)=>a+b,0);
  return {columns:['Quarter','Revenue (demo units)','Earnings (demo units)'],rows:s[0].map((v,i)=>['Q'+(i+1),v,s[1][i]]),series:['Revenue','Earnings'],unit:'units',metrics:[['Annual revenue',revenue+' units'],['Annual earnings',earnings+' units'],['Earnings / revenue',(earnings/revenue*100).toFixed(1)+'%']]};
 }
 if(key==='score'){
  const bands=['300–499','500–599','600–699','700–799','800–850'];const sets={all:[35,105,290,410,160],new:[28,62,123,74,13],established:[7,43,167,336,147]};const values=sets[selection];if(!values)throw new Error('Invalid cohort');const total=values.reduce((a,b)=>a+b,0);return {columns:['Demonstration band','Profiles'],rows:values.map((v,i)=>[bands[i],v]),series:['Profiles'],unit:'profiles',metrics:[['Profiles in cohort',total.toLocaleString('en-US')],['Largest band',bands[values.indexOf(Math.max(...values))]],['Bands explored','5']]};
 }
 if(key==='risk'){
  const threshold=Number(selection);if(!Number.isFinite(threshold)||threshold<300||threshold>850)throw new Error('Invalid threshold');const filtered=sampleLoans.filter(r=>r.score>=threshold),balance=filtered.reduce((a,r)=>a+r.balance,0);return {columns:['Sample record','Score','Balance (demo units)'],rows:filtered.map(r=>[r.id,r.score,r.balance.toLocaleString('en-US')]),series:['Score'],unit:'score',metrics:[['Matching records',String(filtered.length)+' / '+sampleLoans.length],['Sample balance',balance.toLocaleString('en-US')+' units'],['Minimum score',String(threshold)]]};
 }
 const groups={department:[['Engineering',240,24],['Sales',180,36],['Operations',120,18],['People',60,6]],overtime:[['With overtime',180,45],['Without overtime',420,39]]};const values=groups[selection];if(!values)throw new Error('Invalid grouping');const total=values.reduce((a,r)=>a+r[1],0),left=values.reduce((a,r)=>a+r[2],0);return {columns:['Group','Attrition rate (%)','Employees','Departures'],rows:values.map(([label,n,l])=>[label,+(l/n*100).toFixed(1),n,l]),series:['Attrition rate'],unit:'%',metrics:[['Sample employees',String(total)],['Sample departures',String(left)],['Overall attrition',(left/total*100).toFixed(1)+'%']]};
}
